### PR TITLE
Issue 527 - Implement PATCH

### PR DESCRIPTION
**Pull request by whikloj**
**GitHub Issue**: Islandora-CLAW/CLAW#527

## **DON'T MERGE YET**

# What does this Pull Request do?

Implements custom handling of PATCH requests for fedora_resource entities.

# What's new?

1. Override the default rest plugin definition to use our FedoraResourceEntity class (via the hook_rest_resource_alter)
2. In FedoraResourceEntity, alter the request handler for PATCH requests to use our own FedoraRestRequestHandler (getBaseRoute() line 180)
3. In FedoraRestRequestHandler check for and pass in X-Islandora-Bundle headers to make available during denormalization.

# How should this be tested?

I have tried to make some tests, but mocking the REST module is a pain. They offer some functional tests, but I a) don't understand them and b) haven't been able to get them to run really at all.

@Islandora-CLAW/committers

### CODE REVIEW

**Comment by DiegoPino** [comment]
@whikloj there is still time before this gets merged so could give you a hand with the tests. I would directly go for WebTests (http integration) since the details/internalities of this class are kinda handled by the extended class (front) or by the backend (denormalizer).

**Comment by dannylamb** [comment]
phpcbf should take care of shortening those arrays for ya.  I think we'll have to use those going forward forever now b/c of recent Drupal code style updates.

**Comment by whikloj** [comment]
I'll get on the arrays, most of this stuff is copied directly from the inherited class and then modified which is where those `array()`s come from. 

The rest module has functional tests to inherit that are supposed to test all available methods. They suggest you base them off of [EntityResourceTestBase](https://api.drupal.org/api/drupal/core!modules!rest!tests!src!Functional!EntityResource!EntityResourceTestBase.php/class/EntityResourceTestBase/8.2.x) much like (the one I was trying to follow) [NodeResourceTestBase](https://api.drupal.org/api/drupal/core%21modules%21rest%21tests%21src%21Functional%21EntityResource%21Node%21NodeResourceTestBase.php/8.2.x).

However I was trying to run the `rest` test group which these are a part of....and they fail. I tried with phantomjs running and same thing. So I think I am missing something...

As for `phpcbf`...yeah on my Mac I still don't get any warning about using the short array codes. Perhaps I need to update my `drupal/coder`?

**Comment by whikloj** [comment]
@ruebot what version of coder are you running and when you say you updated the sniff file. What was involved?

**Comment by DiegoPino** [comment]
@whikloj 
phpcs --version
PHP_CodeSniffer version 2.8.1 (stable) by Squiz (http://www.squiz.net)

composer global info drupal/coder
Changed current directory to /Users/dpino/.composer
name     : drupal/coder
descrip. : Coder is a library to review Drupal code.
keywords : code review, phpcs, standards
versions : * 8.2.12
type     : phpcodesniffer-standard
license  : GPL-2.0+
source   : [git] https://github.com/klausi/coder.git 984c54a7b1e8f27ff1c32348df69712afd86b17f
dist     : [zip] https://api.github.com/repos/klausi/coder/zipball/984c54a7b1e8f27ff1c32348df69712afd86b17f 984c54a7b1e8f27ff1c32348df69712afd86b17f
names    : drupal/coder

requires
ext-mbstring *
php >=5.4.0
squizlabs/php_codesniffer >=2.8.1 <3.0
symfony/yaml >=2.0.0

requires (dev)
phpunit/phpunit >=3.7 <6

**Comment by dannylamb** [comment]
While it makes sense given our current predicament with Rules, _I do not want a precedent to be set where it's acceptable to provide code without tests_.  I know that @whikloj has already written the tests and is waiting for an upstream PR to land, so it's an allowance I'm willing to make now.  But do not expect this to happen in the future.  Accepting code without tests is more of a burden than writing them in the first place.  And if it becomes a practice, we're setting a terrible example for the contributors who are learning by working with us.

We should engage with the Drupal community to grease the wheels on https://github.com/fago/rules/pull/480 so these test can be written.  And in the very least we should make an issue to do so in our queue so it doesn't slip through the cracks.

That said, it's great work @whikloj and I'll start a formal review soon.  Thanks for jumping down some scary rabbit holes to make this happen.

**Comment by DiegoPino** [comment]
@dannylamb so good to read your statement here: tests are necessary and god forgive us if we give new committers a bad impression or example. Consistency is good. 

But in this particular case, I wonder if the deeper issue has some solution immediate solution or maybe just waiting? I mean, yeah, Tests can go here, but as they are, merging should be a no if they fail right?. Or maybe just WebTests and checking for general integration? Supporting all solutions of course.

I keep having errors on `rules`, like a simple new content operation is giving (see below) a bunch of notices, probably not that bad but would break any tests. Wonder why our other tests are passing, though. 

Maybe @whikloj could make 2 pull request? This one and then one single for the Tests so those can be merged when `rules` accepts that pull? Just an idea. Anyway.

Thanks 😄 

````
http://localhost:8000|1490901834|php|10.0.2.2|http://localhost:8000/fedora_resource/add/non_rdf_source|http://localhost:8000/fedora_resource/add/non_rdf_s

  #1 [internal function]: _drupal_error_handler(2, 'preg_match_all(...', '/var/www/html/d...', 186, Array)
                                   #2 /var/www/html/drupal/web/modules/contrib/typed_data/src/PlaceholderResolver.php(186): preg_match_all('/\n      \\{\\{   ...', Array, NULL)
                                   #3 /var/www/html/drupal/web/modules/contrib/rules/src/Plugin/RulesDataProcessor/TokenProcessor.php(63): Drupal\typed_data\PlaceholderResolver->scan(Array)
                                   #4 /var/www/html/drupal/web/modules/contrib/rules/src/Context/ContextHandlerTrait.php(294): Drupal\rules\Plugin\RulesDataProcessor\TokenProcessor->process
                                   #5 /var/www/html/drupal/web/modules/contrib/rules/src/Context/ContextHandlerTrait.php(85): Drupal\rules\Plugin\RulesExpression\RulesAction->processData(Ob
                                   #6 /var/www/html/drupal/web/modules/contrib/rules/src/Plugin/RulesExpression/RulesAction.php(92): Drupal\rules\Plugin\RulesExpression\RulesAction->prepare
                                   #7 /var/www/html/drupal/web/modules/contrib/rules/src/Plugin/RulesExpression/ActionSet.php(31): Drupal\rules\Plugin\RulesExpression\RulesAction->executeWi
                                   #8 /var/www/html/drupal/web/modules/contrib/rules/src/Plugin/RulesExpression/Rule.php(94): Drupal\rules\Plugin\RulesExpression\ActionSet->executeWithState
                                   #9 /var/www/html/drupal/web/modules/contrib/rules/src/Plugin/RulesExpression/ActionSet.php(31): Drupal\rules\Plugin\RulesExpression\Rule->executeWithState
                                   #10 /var/www/html/drupal/web/modules/contrib/rules/src/EventSubscriber/GenericEventSubscriber.php(131): Drupal\rules\Plugin\RulesExpression\ActionSet->exe
                                   #11 /var/www/html/drupal/web/core/lib/Drupal/Component/EventDispatcher/ContainerAwareEventDispatcher.php(111): Drupal\rules\EventSubscriber\GenericEventSu
                                   #12 /var/www/html/drupal/web/modules/contrib/rules/rules.module(124): Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch('rules_enti
                                   #13 [internal function]: rules_entity_insert(Object(Drupal\islandora\Entity\FedoraResource))
                                   #14 /var/www/html/drupal/web/core/lib/Drupal/Core/Extension/ModuleHandler.php(402): call_user_func_array('rules_entity_in...', Array)
                                   #15 /var/www/html/drupal/web/core/lib/Drupal/Core/Entity/EntityStorageBase.php(169): Drupal\Core\Extension\ModuleHandler->invokeAll('entity_insert', Array
                                   #16 /var/www/html/drupal/web/core/lib/Drupal/Core/Entity/ContentEntityStorageBase.php(418): Drupal\Core\Entity\EntityStorageBase->invokeHook('insert', Obj
                                   #17 /var/www/html/drupal/web/core/lib/Drupal/Core/Entity/EntityStorageBase.php(470): Drupal\Core\Entity\ContentEntityStorageBase->invokeHook('insert', Obj
                                   #18 /var/www/html/drupal/web/core/lib/Drupal/Core/Entity/ContentEntityStorageBase.php(304): Drupal\Core\Entity\EntityStorageBase->doPostSave(Object(Drupal
                                   #19 /var/www/html/drupal/web/core/lib/Drupal/Core/Entity/EntityStorageBase.php(395): Drupal\Core\Entity\ContentEntityStorageBase->doPostSave(Object(Drupal
                                   #20 /var/www/html/drupal/web/core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php(761): Drupal\Core\Entity\EntityStorageBase->save(Object(Drupal\is
                                   #21 /var/www/html/drupal/web/core/lib/Drupal/Core/Entity/Entity.php(364): Drupal\Core\Entity\Sql\SqlContentEntityStorage->save(Object(Drupal\islandora\Ent
````

**Comment by dannylamb** [comment]
@DiegoPino  As I previously stated, I am aware of the particulars of the bug and agreeable to accepting the work without tests after review.

**Comment by whikloj** [comment]
I have the beginning of tests [here](https://github.com/whikloj/islandora-1/tree/issue-527-tests/tests/src/Functional) and I'll move forward once we get that Rules thing sorted out.

**Comment by jonathangreen** [comment]
As per: https://www.drupal.org/node/2824348. The issue we were tracking is closed as a duplicate. I made a new PR here that will hopefully get merged:
https://github.com/fago/rules/pull/484

**Comment by jonathangreen** [comment]
🎉 patch was finally merged in rules!

**Comment by whikloj** [comment]
Coming back around to this, which should be closed as we no longer use our own entities. 

I was looking at re-implementing for Drupal. But I am unclear how we tell when a PATCH is acting against an Islandora resource and so the VersionCounter should have an impact and when we are acting on a normal Drupal resource and so we should get out of the way.

**Comment by dannylamb** [comment]
@whikloj There's no way to tell the difference between our content models and others.  But I think given what I figured out with https://github.com/Islandora-CLAW/islandora/pull/71/files#diff-d853795a5c64eb8e7cf35c30c0c41356, we can utilize the version counter a bit differently.  With a middleware, we can inject in the route match so we can get our hands on the object, and then reject PATCH requests based on a header containing the version count.  This would work for all nodes, not just our special content types.

**Comment by dannylamb** [comment]
@whikloj And yeah, close away.

**Comment by whikloj** [comment]
@dannylamb is there a way to determine what event you can/should listen to. So we do this check at the correct time in the request?

**Comment by whikloj** [comment]
I found it https://api.drupal.org/api/drupal/core%21core.api.php/group/events/8.4.x

**Pull request closed without merging**
