### PR TITLE
Rules actions for event message

### PR DESCRIPTION
**Pull request by dannylamb**
Resolves https://github.com/Islandora-CLAW/CLAW/issues/450
See the associated install PR https://github.com/Islandora-CLAW/CLAW/pull/451

This PR has three rules actions, one to create each type of event message.  It packages those actions into three reaction rules.  Since https://github.com/Islandora-CLAW/CLAW/issues/448 and https://github.com/Islandora-CLAW/CLAW/issues/432 are still on the go, we simple print the event messages to the screen instead actually doing any queue publishing.

It also comes with more Kernel tests for the actions, along with a healthy refactoring of the tests so phpcpd doesn't complain and PHPUnit has info on code coverage.

### To test
- Uninstall islandora
- Install `typed_data` and `rules` modules
- Pull down this PR
- Re-install islandora
- Verify the rules have installed themselves by visiting `admin/config/workflow/rules`
screenshot from 2016-12-09 15-54-58
- Go to edit the rules to verify there are two actions, one for generating the message and another to display it
screenshot from 2016-12-09 15-55-39
- Then go create a FedoraResource, and a create event message should be dsm'd to the screen
screenshot from 2016-12-09 15-56-31
- Edit the entity, and you should see an update event message
screenshot from 2016-12-09 15-57-16
- Delete the entity and you should see a delete event message
screenshot from 2016-12-09 15-57-45

### CODE REVIEW

**Comment by dannylamb** [comment]
Hrm... looks like I've got some bad history on this.  Give me a moment to clean this up.

**Comment by dannylamb** [comment]
@Islandora-CLAW/committers ok, i've cleaned this up and also issued an install PR https://github.com/Islandora-CLAW/CLAW/pull/451.

And please, don't just merge this, _SQUASH AND MERGE THIS_

**Comment by Natkeeran** [comment]
@dannylamb @whikloj I've tested this by following the instructions.  Works as expected.

**Comment by dannylamb** [comment]
@Natkeeran Thanks so much for testing.  

I originally tried stripping the UUID's out, but it broke the UI and you couldn't go to edit the actions for any of the rules.  I'd prefer they weren't in there.  In fact, I was worried that they might lead to config entity conflicts and we'd have to find a different way of packaging them.  So I'm relieved it worked for you.

**Comment by whikloj** [comment]
@dannylamb 😢  I'm soooo sorry I totally forgot to Squash this. I can fix this with an extra commit if your okay with that.

**Comment by whikloj** [comment]
@dannylamb I lied, I'd need to revert this to squash it. Otherwise I have to force push and overwrite the history. Maybe we leave the commits and my sincere apologies.

**Comment by DiegoPino** [comment]
@Natkeeran @dannylamb the UUID should and is needed so no worries about that 😄 , more over, avoid stripping them. Configs files are entities also (you can look at the class that loads them) and all entities need uuids, so needed here also and we must respect this. The danger of conflict because of reuse of the same uuid is little to none.

**Comment by dannylamb** [comment]
@DiegoPino++ Learn something new every day.

**Comment by dannylamb** [comment]
@whikloj Don't worry about it.

**Pull request merged**
