### PR TITLE
Check derivative term

### PR DESCRIPTION
**Pull request by kayakr**
**GitHub Issue**: (link)
https://github.com/Islandora/documentation/issues/1475

* Other Relevant Links (Google Groups discussion, related pull requests,
 Release pull requests, etc.)

# What does this Pull Request do?

Fixes a check for `$derivative_term` after it has been fetched by URI.

# What's new?
Should trap cases where a derivative term can't be located by URI.

# How should this be tested?

* Add a Repository Item with Model=Image
* Add media, type=Image, Use=Original Term
* When media is submitted, and derivatives generated, you might see an error message "Error generating event: Could not locate derivative term with urihttps://projects.iq.harvard.edu/fits"

# Interested parties
@Islandora-CLAW/committers

### CODE REVIEW

**Comment by whikloj** [comment]
@kayakr this looks bigger then it is. Could you grab the dev branch and just cherry-pick the https://github.com/Islandora-CLAW/islandora/pull/181/commits/1ca7b5911935fb3f0155b3e583734112befe3d65 and https://github.com/Islandora-CLAW/islandora/pull/181/commits/a2ae41a976b6d6ee203fa3422049fbe970179a20 commits on to it?

```bash
> git checkout -b new-pr origin/dev
> git cherry-pick 1ca7b5911935fb3f0155b3e583734112befe3d65
> git cherry-pick a2ae41a976b6d6ee203fa3422049fbe970179a20
```

That "should" do it.

**Comment by seth-shaw-unlv** [comment]
Also, this is on the old repo. New work should be done on the new one https://github.com/Islandora/islandora/tree/8.x-1.x/.

**Comment by whikloj** [comment]
Ohhhh right maybe that's why it has so many commits.

**Comment by dannylamb** [comment]
:man_facepalming:

**Comment by kayakr** [comment]
@whikloj @seth-shaw-unlv @dannylamb Sorry everyone, I'd made a PR based on a stale fork. I'll blow it away and do a new PR...

**Comment by kayakr** [comment]
@dannylamb While I'm here, if I visit https://github.com/islandora/documentation and click on the link to `islandora @` in the left sidebar, it takes me to the old repo https://github.com/Islandora-CLAW/islandora/tree/28c74495c8a2d5a2b63d02b90a973027f0da8caa; there's a message there to say "don't use" but can the link on the sidebar be updated?

**Comment by kayakr** [comment]
Better PR at https://github.com/Islandora/islandora/pull/766

**Pull request closed without merging**
