### PR TITLE
Issue 1290 fix

### PR DESCRIPTION
**Pull request by dflitner**
**GitHub Issue**: https://github.com/Islandora-CLAW/CLAW/issues/1290

# What does this Pull Request do?

Replaces instances of string 'field_external_uri' with constant EXTERNAL_URI_FIELD.

# How should this be tested?

Create Repository Items and check the watchdog log.

# Interested parties
@Islandora-CLAW/committers

### CODE REVIEW

**Comment by whikloj** [comment]
Nice work @dflitner, Travis is catching on a long line here. You may need to wrap that comment to 3 lines 😱 
Error -> https://travis-ci.com/Islandora-CLAW/islandora/jobs/241313512#L1272-L1276
Code -> https://github.com/Islandora-CLAW/islandora/pull/176/files#diff-e8c26f1d215b9585386ff37c3b0bfab0R50

**Comment by dannylamb** [comment]
Looks good to me.

@manez Are we good on the CLA front?  I'd like to merge this.

**Comment by dflitner** [comment]
Eli helped! (a lot)

**Comment by elizoller** [comment]
ASU should have an institutional CLA I think.

**Comment by whikloj** [comment]
They do, @dannylamb you can press the button.

**Pull request merged**
