### PR TITLE
Using actual release of jsonld

### PR DESCRIPTION
**Pull request by dannylamb**
**GitHub Issue**: Part of Islandora-CLAW/CLAW#950

# What does this Pull Request do?

I just sliced a release of `jsonld` and this changes `compser.json` to use it instead of `dev-master`.

# Interested parties
Another easy one @Islandora-CLAW/committers

### CODE REVIEW

**Comment by whikloj** [comment]
Looking at [packagist.org](https://packagist.org/packages/islandora/jsonld) you either want `dev-8.x-1.x` or `0.0.1`. I'd go for `0.0.1`

**Comment by acoburn** [comment]
I think you actually would want `0.1.0` as an initial release. `0.0.1` would be the first patch of version `0.0`, whereas `0.1.0` would be the first release of version `0.1`, but that's (admittedly) pretty nit-picky.

**Comment by dannylamb** [comment]
Ah yeah, I derped and initially sliced 0.0.1 instead of following drupal's ridiculous 8.x-1.x convention.  I renamed the tag to 8.x-0.1, but packagist doesn't want to update it.  I'll have to go mess around to see if I can get it to refresh tags, or otherwise delete and slice a new release or something.

Was thinking it'd be 8.x-0.1 now and then 8.x-1.0 when released.  That's about as much sense as I can make out of it. :man_shrugging:

**Comment by whikloj** [comment]
@dannylamb Coming back around to this, I'm going to cut a `0.1.0` release of [jsonld](https://github.com/Islandora-CLAW/jsonld) as @acoburn suggests above and then if you want to update this PR to reference that I'll merge it in.

**Comment by dannylamb** [comment]
@whikloj Unfortunately, we're bound to Drupal's wacky versioning policy, and have to do the `8x-X.X` thing :(

**Comment by whikloj** [comment]
@dannylamb for development branches I think you are right, but for releases (based on coder) it appears that you can have a number.
https://packagist.org/packages/drupal/coder

**Comment by whikloj** [comment]
Also, seemingly related https://www.drupal.org/project/drupal/issues/1612910

**Comment by dannylamb** [comment]
Well that changes things.  I mean... a lot... We can finally give proper versions to all our drupal modules :smile:

**Comment by dannylamb** [comment]
Thx @whikloj and @acoburn, this is finally ready.

**Comment by whikloj** [comment]
@dannylamb 
1. ideas how to test this, or do we just merge it and give it a try.
1. your branch is "out-of-date" again 😡 I really want to remove that requirement and am adding it to the [agenda for today's call](https://github.com/Islandora-CLAW/CLAW/wiki/May-8,-2019)

**Comment by dannylamb** [comment]
Handled this as part of the release.  We're on proper semantic versioning for everything now, even Drupal modules :champagne:

**Pull request closed without merging**
