### PR TITLE
Add binary to node

### PR DESCRIPTION
**Pull request by dannylamb**
**GitHub Issue**: Resolves https://github.com/Islandora-CLAW/CLAW/issues/796, depends on https://github.com/Islandora-Devops/claw-playbook/pull/57

# What does this Pull Request do?

Adds a route that lets users add new Media to Nodes by issuing POST requests.

# What's new?
A new controller method and custom access check. The route is located at `node/{node}/media/{field}/add/{bundle}`. There's tests to assert the following behaviours:

- It returns 404 if none of the route parameters exist in Drupal.
- It returns 403 if you do not have permissions to update the Node nor create a Media entity.
- It requires a request body, returning 400 if missing.
- It expects a `Content-Disposition` header of the form `attachment; filename="your_filename_with_extension"`, returning 400 if missing.
- It expects a `Content-Type` header, returning 400 if missing.
- It returns 201 on success, with a `Location` header pointing to the created Media.
- If the Node already has a Media referenced by the specified field, it returns 409 (Conflict).  If you want to update an existing media, PUT content to the `/media/{media}/source` route from https://github.com/Islandora-CLAW/CLAW/issues/787 instead.

# How should this be tested?

Pull down this code, and clear drupal caches and routing.
- `drupal cache:rebuild all`
- `drupal router:rebuild`

Using ths JSON:
```json
{
   "type":[
      {
         "target_id":"islandora_image",
         "target_type":"node_type"
      }
   ],
   "title":[
      {
         "value":"Title goes here."
      }
   ],
   "field_description":[
      {
         "value":"Description goes here."
      }
   ]
}
```

Create a new `islandora_image` node using the REST api: 
- Save the JSON to a file, I named mine `image.json`.
```
curl -u admin:islandora -H "Content-Type: application/json" --data-binary @image.json -v localhost:8000/node
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8000 (#0)
* Server auth using Basic with user 'admin'
> POST /node HTTP/1.1
> Host: localhost:8000
> Authorization: Basic YWRtaW46aXNsYW5kb3Jh
> User-Agent: curl/7.47.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 272
> 
* upload completely sent off: 272 out of 272 bytes
< HTTP/1.1 201 Created
< Date: Mon, 12 Feb 2018 15:18:05 GMT
< Server: Apache/2.4.18 (Ubuntu)
< X-Powered-By: PHP/7.0.22-0ubuntu0.16.04.1
< Location: http://localhost:8000/node/4
< Cache-Control: must-revalidate, no-cache, private
< X-UA-Compatible: IE=edge
< Content-language: en
< X-Content-Type-Options: nosniff
< X-Frame-Options: SAMEORIGIN
< Expires: Sun, 19 Nov 1978 05:00:00 GMT
< X-Generator: Drupal 8 (https://www.drupal.org)
< Content-Length: 1145
< Content-Type: application/json
< 
{"nid":[{"value":4}],"uuid":[{"value":"42045e71-5672-4068-88fe-81d0a1c6d563"}],"vid":[{"value":6}],"langcode":[{"value":"en"}],"type":[{"target_id":"islandora_image","target_type":"node_type","target_uuid":"a1746dab-a9c1-4716-86b8-f7ee220a1c46"}],"revision_timestamp":[{"value":"2018-02-12T15:18:05+00:00","format":"Y-m-d\\TH:i:sP"}],"revision_uid":[{"target_id":1,"target_type":"user","target_uuid":"a18b74b4-22a0-446d-ab39-1e9b46dc7c39","url":"\/user\/1"}],"revision_log":[],"status":[{"value":true}],"title":[{"value":"Title goes here."}],"uid":[{"target_id":1,"target_type":"user","target_uuid":"a18b74b4-22a0-446d-ab39-1e9b46dc7c39","url":"\/user\/1"}],"created":[{"value":"2018-02-12T15:18:05+00:00","format":"Y-m-d\\TH:i:sP"}],"changed":[{"value":"2018-02-12T15:18:05+00:00","format":"Y-m-d\\TH:i:sP"}],"promote":[{"value":true}],"sticky":[{"value":false}],"default_langcode":[{"value":true}],"revision_translation_affected":[{"value":true}],"path":[{"alias":null,"pid":null,"langcode":"en"}],"field_description":[{"v* Connection #0 to host localhost left intact
alue":"Description goes here."}],"field_jp2":[],"field_memberof":[],"field_tiff":[],"field_tn":[],"field_web_content":[]}
```

In the response, you should be given a `Location` header telling you where the new Node is located. Mine was `Location: http://localhost:8000/node/4`.  Check out the node, it should be blank except for the title and descriptions we supplied in the JSON.

Now we can add a Media by supplying a binary to a route that contains the Media bundle to create an the field to reference it with.  To add a Tiff, the route would be `http://localhost:8000/node/4/media/field_tiff/add/image_tiff`.  To add a regular png or jpeg, you would use `http://localhost:8000/node/4/media/field_web_content/add/web_content` 

Let's try it out with a JPEG.  Assuming we have a jpeg named `test.jpeg`:
```
daniel@daniel-Latitude-3560:~/Pictures$ curl -v -u admin:islandora -H "Content-Type: image/jpeg" -H "Content-Disposition: attachment; filename=\"test.jpeg\"" --data-binary @test.jpeg http://localhost:8000/node/4/media/field_web_content/add/web_content
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8000 (#0)
* Server auth using Basic with user 'admin'
> POST /node/4/media/field_web_content/add/web_content HTTP/1.1
> Host: localhost:8000
> Authorization: Basic YWRtaW46aXNsYW5kb3Jh
> User-Agent: curl/7.47.0
> Accept: */*
> Content-Type: image/jpeg
> Content-Disposition: attachment; filename="test.jpeg"
> Content-Length: 7119
> Expect: 100-continue
> 
< HTTP/1.1 100 Continue
* We are completely uploaded and fine
< HTTP/1.1 201 Created
< Date: Mon, 12 Feb 2018 15:34:44 GMT
< Server: Apache/2.4.18 (Ubuntu)
< X-Powered-By: PHP/7.0.22-0ubuntu0.16.04.1
< Cache-Control: must-revalidate, no-cache, private
< Location: http://localhost:8000/media/3
< X-UA-Compatible: IE=edge
< Content-language: en
< X-Content-Type-Options: nosniff
< X-Frame-Options: SAMEORIGIN
< Expires: Sun, 19 Nov 1978 05:00:00 GMT
< X-Generator: Drupal 8 (https://www.drupal.org)
< Content-Length: 0
< Content-Type: text/html; charset=UTF-8
< 
* Connection #0 to host localhost left intact
```

Your new Media's url is returned as the `Location` header in the response.  Mine was `Location: http://localhost:8000/media/3`.  Now go visit the media and check out the node to make sure it's referenced.

# Interested parties
@Islandora-CLAW/committers

### CODE REVIEW

**Comment by whikloj** [comment]
So this looks (and I could be wrong) like it takes an uploaded file, makes a new Media and attaches it to the node entity. What if the file has already been uploaded once? Normally Drupal just re-uses the existing File entity to avoid a second copy...does that work here too?

**Comment by dannylamb** [comment]
@whikloj Currently, no, it will introduce duplicates.  I call `file_validate_extension` manually, but _should_ be able to hook into the duplicate prevention code with `file_validate`.  I initially tried that but it gave me trouble and in the interest of time I moved on.  Maybe it's worth exploring now that I'm not rushing myself.

**Comment by whikloj** [comment]
As long as I am understanding it, we can move forward with this in the interest of time and open a new ticket to revisit the file duplication issue later.

**Comment by mjordan** [comment]
I can also confirm this PR works. Am fixing up my script to ingest a small batch of nodes with files, will post here just for fun.

**Comment by mjordan** [comment]
Works in curl but not using Guzzle or httpful... both of those fail to authenticate (403) using Basic Authentication. See https://github.com/mjordan/claw_rest_ingester, which includes an `ingest.php` script that reads a CSV file and attempts to ingest each entry using a Guzzle client, and a simpler script that just attempts to create a node using the httpful client library. I've also tried using the [RESTClient](https://addons.mozilla.org/en-US/firefox/addon/restclient/) Firefox plugin. All return 403.

Of course, the failure to authenticate using both of those clients could be a PEBCAK error.... but has anyone else been able to execute any REST requests requiring authentication using anything other than curl?

**Comment by mjordan** [comment]
For reference, when I use Guzzle's `'dump' => true` client option, here's the output:


```
* Connection #0 to host localhost left intact
* Found bundle for host localhost: 0x2919dd0
* Re-using existing connection! (#0) with host localhost
* Connected to localhost (127.0.0.1) port 8000 (#0)
> POST /node HTTP/1.1
User-Agent: GuzzleHttp/6.2.1 curl/7.35.0 PHP/5.5.9-1ubuntu4.23
Authorization: Basic YWRtaW46aXNsYW5kb3Jh
Host: localhost:8000
Content-Type: application/json
Content-Length: 185

* upload completely sent off: 185 out of 185 bytes
< HTTP/1.1 403 Forbidden
< Date: Thu, 01 Mar 2018 05:20:36 GMT
* Server Apache/2.4.18 (Ubuntu) is not blacklisted
< Server: Apache/2.4.18 (Ubuntu)
< X-Powered-By: PHP/7.0.25-0ubuntu0.16.04.1
< Cache-Control: must-revalidate, no-cache, private
< X-Drupal-Dynamic-Cache: UNCACHEABLE
< X-UA-Compatible: IE=edge
< Content-language: en
< X-Content-Type-Options: nosniff
< X-Frame-Options: SAMEORIGIN
< Expires: Sun, 19 Nov 1978 05:00:00 GMT
< X-Generator: Drupal 8 (https://www.drupal.org)
< Transfer-Encoding: chunked
< Content-Type: text/html; charset=UTF-8
```

**Comment by mjordan** [comment]
Uh... can't explain this, but creating an islandora_image node using https://chrome.google.com/webstore/detail/restlet-client-rest-api-t/aejoelaoggembcahagimdiliamlcdmfm (same credentials, JSON body, etc. as with other clients) worked.

**Comment by mjordan** [comment]
The plot thickens. RESTClient for Firefox (which fails) provides the raw curl equivalent for its requests. In this case, it's

```
curl -X POST -H 'Content-Type: application/json' -H 'Authorization: Basic YWRtaW46aXNsYW5kb3Jh' -i http://localhost:8000/node --data '{"type":[{"target_id":"islandora_image","target_type":"node_type"}],"title":[{"value":"Test title"}],"field_description":[{"value":"Test description."}]}'
```

This works (returns 210, and I confirmed that the node UUID matches the one returned).

I notice that the Basic Authorization has been hashed. That's how the server needs to receive it, and I would expect all clients to hash the credentials in using Basic authentication. Looks like curl checks to see if they're already hashed and doesn't rehash them.

Very strange though that this Firefox plugin would fail but the raw curl version of the request it issues would succeed.

**Comment by mjordan** [comment]
OK, figured it out for Guzzle. Providing Basic Authentication in a header instead of using the `auth` client option works:

`'headers' => array('Authorization' => 'Basic YWRtaW46aXNsYW5kb3Jh', 'Content-Type' => 'application/json')`

Results in the nodes being ingested:
```
Node "Small boats in Havana Harbour" (http://localhost:8000/node/13) created, with image from input_data/IMG_1410.JPG.
Node "Manhatten Island" (http://localhost:8000/node/14) created, with image from input_data/IMG_2549.JPG.
Node "Looking across Burrard Inlet" (http://localhost:8000/node/15) created, with image from input_data/IMG_2940.JPG.
Node "Amsterdam waterfront" (http://localhost:8000/node/16) created, with image from input_data/IMG_2958.JPG.
Node "Alcatraz Island" (http://localhost:8000/node/17) created, with image from input_data/IMG_5083.JPG.
```

Success has revealed a couple other issues I don't have time to fix at the moment but at least I've resolved my 403 issue.

**Comment by mjordan** [comment]
OK, https://github.com/mjordan/claw_rest_ingester now works. @whikloj if you have  minute, give it a try.

**Comment by mjordan** [comment]
Added logic to https://github.com/mjordan/claw_rest_ingester to support ingesting TIFF and JP2 binaries but I can't figure out the correct routes (`/media/field_tiff/add/image_tiff` and `/media/field_jp2/add/jp2` don't work).

**Comment by mjordan** [comment]
Sweet. @dannylamb when you have a minute, could you let me now which routes to use to add TIFFs and JP2? Not urgent.

**Pull request merged**
