### PR TITLE
#1187 Update EVA to 8.x-2.0

### PR DESCRIPTION
**Pull request by kayakr**
**GitHub Issue**: https://github.com/Islandora/documentation/issues/1187

# What does this Pull Request do?

Update EVA from 8.x-1.3 (unsupported) to 8.x-2.0 (from 5 Nov 2019).

# What's new?
From EVA release notes, "The 2.0 branch is a big refactor of hastily converted Drupal 7 code and includes some fixes and new features. Upgrading from 1.x should be seamless and not require configuration updates."

# How should this be tested?

A description of what steps someone could take to:
* Apply patch
* `composer update drupal/eva`
* Test views depending on EVA, e.g. Repository Items with PDF, OpenSeadragon displays.

# Interested parties
@Islandora-CLAW/committers

### CODE REVIEW

**Comment by dannylamb** [comment]
Restarting Travis on this.  Looks like it can come right in.

**Comment by kayakr** [comment]
@dannylamb This has been failing to build in Travis for some time, but the issue appears unrelated to EVA. Have you seen the Travis failures elsewhere?

**Comment by dannylamb** [comment]
Ah, beause we're on the old fork :man_facepalming: This one's on me, I moved over all the PRs to https://github.com/Islandora/islandora/pulls save this one, apparantly :sweat_smile:  It was a manual process.  I'll go do that now.

**Comment by dannylamb** [comment]
https://github.com/Islandora/islandora/pull/760

**Pull request closed without merging**
