### PR TITLE
Setup codecov.io on islandora; Addresses https://github.com/Islandora…

### PR DESCRIPTION
**Pull request by ruebot**
…-CLAW/CLAW/issues/544

See: https://github.com/Islandora-CLAW/CLAW/issues/544

This one might be tricky. I'm going to keep an eye on the TravisCI build to make sure it does everything right. Once it does, I'll take care of the other modules listed in the ticket.

### CODE REVIEW

**Comment by dannylamb** [comment]
:pray:

**Comment by mjordan** [comment]
@ruebot thanks for making me laugh :laughing:

**Comment by DiegoPino** [comment]
This is Drupal's [phpunit.xml.dist](http://cgit.drupalcode.org/drupal/tree/core/phpunit.xml.dist)
According to that example and https://www.drupal.org/docs/8/phpunit/running-phpunit-tests we could need a few extra things here.

**Comment by DiegoPino** [comment]
Also from IRC, http://www.pixelite.co.nz/article/writing-phpunit-tests-for-your-custom-modules-in-drupal-8/ looks like a good guide, hope that helps

**Pull request closed without merging**
