### PR TITLE
Enable islandora_core_feature on Travis builds

### PR DESCRIPTION
**Pull request by seth-shaw-unlv**
**GitHub Issue**: Islandora-CLAW/CLAW/issues/1279

# What does this Pull Request do?

Catch bad configs in islandora_core_feature during Travis builds so we don't have to do retro-active PRs like https://github.com/Islandora-CLAW/islandora/pull/169 when we hit failed Travis builds like https://travis-ci.com/Islandora-CLAW/islandora_defaults/jobs/237164283.
# What's new?

* Added a line to the Travis build to enable islandora_core_feature and import the configs ([copied directly from the islandora_defaults build script](https://github.com/Islandora-CLAW/islandora_defaults/blob/8.x-1.x/.travis.yml#L29))
* Does this change require documentation to be updated? No.
* Does this change add any new dependencies? No.
* Does this change require any other modifications to be made to the repository
 (ie. Regeneration activity, etc.)? No.
* Could this change impact execution of existing code? No.

# How should this be tested?

Travis should fail until https://github.com/Islandora-CLAW/islandora/pull/169 gets merged but be happy afterwards.

# Interested parties
@Islandora-CLAW/committers, esp. @dannylamb

### CODE REVIEW

**Comment by dannylamb** [comment]
bit of a waiting game, but Travis should pass now _in theory_

**Comment by seth-shaw-unlv** [comment]
Yeah, it was still chugging along on the older builds so I just cancelled them so the newest ones are now starting up.

**Comment by seth-shaw-unlv** [comment]
Well it passed the new Travis updates! Now it just needs to get through the tests.

**Comment by seth-shaw-unlv** [comment]
@dannylamb green means go!

**Pull request merged**
