### PR TITLE
Nesting islandora in its own folder

### PR DESCRIPTION
**Pull request by dannylamb**
Resolves https://github.com/Islandora-CLAW/CLAW/issues/440.

Just organization, this changes nothing as far as functionality is concerned.

### CODE REVIEW

**Comment by dannylamb** [comment]
@ruebot @whikloj You think it's ok if i rename the `tests` folder to make it hidden?  Better yet just pull out the scripts folder and make that hidden?

**Comment by dannylamb** [comment]
I pushed a change moving the top level tests/scripts directory to a hidden folder.  Let's see if Travis agrees.

**Comment by dannylamb** [comment]
Green means go :)

**Comment by whikloj** [comment]
👍

**Pull request merged**
