### PR TITLE
Patching up UUID param converter

### PR DESCRIPTION
**Pull request by dannylamb**
Addresses https://github.com/Islandora-CLAW/CLAW/issues/411

### CODE REVIEW

**Comment by DiegoPino** [comment]
@dannylamb don't fully understand this pull. Can you add some description?

**Comment by dannylamb** [comment]
The uuid param converter was getting ignored because declaring it of type `entity:fedora_resource` meant the default param converter was always geting chosen.

That's really all that changed.  I replaced the internals with loadEntityByUuid since it essentially does what you were doing, pulling out the storage manager and geting it by key.

**Comment by Natkeeran** [comment]
I have Nov 1 vagrant (b07878e1e1e4475de4165da6db9f9627b624e2fa).  After creating a fedora resource, if I go to the http://localhost:8000/fedora_resource/1 page, I get Page not found error.  If I go to http://localhost:8000/devel/fedora_resource/1 or to http://localhost:8000/admin/structure/fedora_resource/3 I get "The website encountered an unexpected error. Please try again later." error.

Apache error log has the following error entry:
```
[pid 1498] [client 10.0.2.2:39048] Uncaught PHP Exception Symfony\\Component\\Routing\\Exception\\RouteNotFoundException: "Route "entity.fedora_resource.version_history" does not exist." at
/var/www/html/drupal/core/lib/Drupal/Core/Routing/RouteProvider.php line 187, referer: http://localhost:8000/admin/structure/fedora_resource
```

I cannot reproduce the original issue due to this to test #411.  I have seen the above noted issue before, but assumed it was under development.  It is possible that I have not populated the fields properly, or don't have some configuration set properly.  I have a vanilla vagrant with a custom test module.

**Comment by dannylamb** [comment]
That's the same error @whikloj was getting in a different ticket.  So now you guys are getting it too.  Hard for me to fix because I can't reproduce, but I'll give it another full blast/re-clone to see.  I think the easiest solution is to implement that route, and see what breaks from there.

**Comment by dannylamb** [comment]
@ruebot @Natkeeran Just curious if you can tell me what commit of the islandora module you're at off the fresh install?

**Comment by Natkeeran** [comment]
@dannylamb the following is the commit my vagrant islandora is using:
```
commit 8a0fb3c0f2477f32e41b7dc5295b33e9634e2c6e
Author: Jared Whiklo <jwhiklo@gmail.com>
Date:   Mon Jul 18 10:22:56 2016 -0500
```

**Comment by dannylamb** [comment]
Bingo.  That submodule is stuck on an old commit.  Let me see if I can do something about that.

**Comment by Natkeeran** [comment]
Grabbed the latest vagrant (d26069b695afc491253f3007b751db38fe7dd839) and ran the steps described in issue#411.  I am able to reproduce the issue.  And this PR does address the issue for me.  In other words, http://localhost:8000/islandora_uuid/15ad07d8-8997-4b5c-9553-f98f254cd81a works after applying this PR with the above vagrant build for me.

**Pull request merged**
