### PR TITLE
Swapping file and media urls in jsonld

### PR DESCRIPTION
**Pull request by dannylamb**
**GitHub Issue**: Resolves https://github.com/Islandora-CLAW/CLAW/issues/662

Requires https://github.com/Islandora-CLAW/islandora_demo/pull/29 and https://github.com/Islandora-CLAW/Crayfish/pull/68

# What does this Pull Request do?

Swaps media and file urls when altering jsonld with `MappingUriPredicateReaction`.

# What's new?

One line change and a test to confirm its behaviour.

# How should this be tested?

- Make a media and view it's ?_format=jsonld route, you should see something like this (edited for brevity):
```json
{
   "@graph":[
      {
         "@id":"http://localhost:8000/media/1",
         "@type":[
            "http://pcdm.org/models#File",
            "http://pcdm.org/use#OriginalFile"
         ],
         ...
         "http://schema.org/sameAs":[
            {
               "@value":"http://localhost:8000/_flysystem/fedora/2019-05/Flemming-Magic.jpg"
            }
         ]
      },
      ...
   ]
}
```
- Pull changes from https://github.com/Islandora-CLAW/islandora_demo/pull/29 into `islandora_demo`
- Pull changes from https://github.com/Islandora-CLAW/Crayfish/pull/68 into Crayfish
- Pull changes from this PR into `islandora`
- `drush -y fim islandora_demo`
- `drush cr`
- View the ?_format=jsonld route again, and this time you should see
```json
{
   "@graph":[
      {
         "@id":"http://localhost:8000/_flysystem/fedora/2019-05/Flemming-Magic.jpg",
         "@type":[
            "http://pcdm.org/models#File",
            "http://pcdm.org/use#OriginalFile"
         ],
         ...
         "http://www.iana.org/assignments/relation/describedby":[
            {
               "@value":"http://localhost:8000/media/1"
            }
         ]
      },
      ...
   ]
}
```
- Curl the resource in Fedora, and you should see something like this (again, edited for brevity):
```
@prefix rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix iana:  <http://www.iana.org/assignments/relation/> .

<http://localhost:8080/fcrepo/rest/2019-05/Flemming-Magic.jpg>
        rdf:type                    fedora:NonRdfSourceDescription ;
        rdf:type                    <http://pcdm.org/models#File> ;
        rdf:type                    <http://pcdm.org/use#OriginalFile> ;
        rdf:type                    fedora:Binary ;
        rdf:type                    fedora:Resource ;
        rdf:type                    ldp:NonRDFSource ;
        iana:describedby            "http://localhost:8000/media/4" ;
        iana:describedby            <http://localhost:8080/fcrepo/rest/2019-05/Flemming-Magic.jpg/fcr:metadata> ;
```  
- Confirm triplestore indexing by issuing a query similar to this.  Note that you have to use the file's url and not the media's.
```
SELECT ?s ?p ?o WHERE { <http://localhost:8000/_flysystem/fedora/2019-05/Flemming-Magic.jpg> ?p ?o }
```

# Interested parties
@Islandora-CLAW/committers

### CODE REVIEW

**Comment by whikloj** [comment]
@dannylamb is there more work to this? I am seeing in Fedora my media object having a triple of the form
```
<http://localhost:8080/fcrepo/rest/2019-05/wonderful.tiff> iana: describedby <http://localhost:8080/fcrepo/rest/2019-05/wonderful.tiff/fcr:metadata>
```
But not the new describedby for the media?

**Comment by dannylamb** [comment]
@whikloj I'm circling back to this one.  I tested Drupal only and not the full stack.  By the looks of it Fedora is overriding us on `iana:describedby`?  But I'll need to dig a little.

**Comment by dannylamb** [comment]
Nope.  Milliner is failing to strip out things in the jsonld because it's looking for the wrong url as an `@id`.

**Comment by dannylamb** [comment]
@whikloj @rosiel I missed a spot in Crayfish.  There's another PR for it, and I've updated the testing instructions for confirming things in Fedora and the triplestore.  It appears that Fedora adds its own `iana:describedby` triple in addition to what you PUT to it.

**Comment by rosiel** [comment]
I don't know if I screwed something up in the testing (I included the Crayfish pull in /var/www/html/Crayfish, was i supposed to restart anything?) - but now I'm not getting any of the "Drupal RDF" in my Fedora. The /fcr:metadata document is missing the rdf:label, pcdm:fileOf, schema:author, schema:dateCreated, schema:dateModified, schema:sameAs, types pcdm:File, pdcmUse:OriginalFile. An object i put into fedora prior to trying to test this, has all those. 

I might have screwed something up in testing multiple PRs at once (I tried to undo what i did re. webforms) but I'll build a new VM and try testing again after.

**Comment by dannylamb** [comment]
@rosiel Shouldn't have to restart anything.  What you're describing is what was happening before the Crayfish PR, essentially.  Does the milliner log say anything?

**Comment by rosiel** [comment]
Uh, no idea since I destroyed the VM. I'm troubleshooting why it won't come up now.

**Comment by whikloj** [comment]
@dannylamb I am okay with this for the first release.

But we basically need to make this reaction mandatory, which with context nothing is. So perhaps some documentation or something to say this UriMappingReaction must run.

**Comment by whikloj** [comment]
@rosiel I am good with this, and the other 2 associated PRs. When you have had a chance to come around and re-test them you can merge.

**Comment by rosiel** [comment]
👍 works for me. 
```
 iana: describedby
    http://localhost:8000/media/1 
    http://localhost:8080/fcrepo/rest/2019-05/5117153870_35e04234d8_o.jpg/fcr:metadata 
```

**Pull request merged**
